version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend:
    build: ./backend/
    command: /bin/sh -c "rails db:create db:migrate && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=backend
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - RAILS_ENV=development
      - ALLOWED_ORIGINS_URL=http://localhost:8080
      - ALLOWED_HOSTS=host.docker.internal,backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db-data:
  node-modules-data:
