# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'bootsnap', require: false
gem 'mysql2', '~> 0.5'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.2'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'debug', platforms: %i[mri windows]
  gem 'rubocop', require: false
end
