source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.2"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem 'bootsnap', require: false

group :development do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rubocop', require: false
end
